---
- name: Generate Locale
  locale_gen:
    name: en_US.UTF-8
    state: present
  become: true
  become_method: sudo

- name: Set Timezone
  raw: "echo Europe/London > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata"
  become: true
  become_method: sudo

- name: Update apt-cache
  apt:
      update_cache: yes
  become: true
  become_method: sudo

- name: Install Curl
  apt:
      name: curl
      state: latest
  become: true
  become_method: sudo

- name: Install software-properties-common
  apt:
      name: software-properties-common
      state: latest
  become: true
  become_method: sudo

- name: Install build-essential
  apt:
      name: build-essential
      state: latest
  become: true
  become_method: sudo

- name: Install tmux
  apt:
      name: tmux
      state: latest
  become: true
  become_method: sudo

- name: Install bash-completion
  apt:
      name: bash-completion
      state: latest
  become: true
  become_method: sudo

- name: Install git
  apt:
      name: git-core
      state: latest
  become: true
  become_method: sudo

- name: Install vim
  apt:
      name: vim
      state: latest
  become: true
  become_method: sudo

- name: Install vim-gui-common
  apt:
      name: vim-gui-common
      state: latest
  become: true
  become_method: sudo

- name: Install vim-runtime
  apt:
      name: vim-runtime
      state: latest
  become: true
  become_method: sudo

- name: Install powerline
  apt:
      name: powerline
      state: latest
  become: true
  become_method: sudo

- name: Create dotfiles dir
  file:
      path: '/home/{{ username }}/.dotfiles'
      state: directory
      owner: '{{ username }}'
      group: '{{ groupname }}'
      mode: 0775

- name: Clone dotfiles
  git:
      repo: 'https://github.com/jcannava/dotfiles'
      dest: '/home/{{ username }}/.dotfiles'

- name: Deploy dotfiles
  shell: '. /home/{{ username }}/.dotfiles/deploy.sh'
  args:
      creates: '/home/{{ username }}/.bashrc.orig'

- name: Get git-prompt.sh
  raw: 'wget -O /home/{{ username }}/.dotfiles/git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh'

- name: Make .vim dir for colorscheme
  file:
      path: '/home/{{ username }}/.vim/pack/themes/opt'
      state: directory
      owner: '{{ username }}'
      group: '{{ groupname }}'
      mode: 0775

- name: Install colorscheme
  git:
      repo: 'https://github.com/lifepillar/vim-solarized8.git'
      dest: '/home/{{ username }}/.vim/pack/themes/opt/solarized8'

- name: Make vim autoload directory
  file:
      path: '/home/{{ username }}/.vim/autoload'
      state: directory
      owner: '{{ username }}'
      group: '{{ groupname }}'
      mode: 0775

- name: Make vim bundle directory
  file:
      path: '/home/{{ username }}/.vim/bundle'
      state: directory
      owner: '{{ username }}'
      group: '{{ groupname }}'
      mode: 0775

- name: Install pathogen (vim)
  raw: 'wget -O /home/{{ username }}/.vim/autoload/pathogen.vim https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim'

- name: Install vim-flake8
  git:
      repo: 'https://github.com/nvie/vim-flake8'
      dest: '/home/{{ username }}/.vim/bundle/vim-flake8'

- name: Install vim-go
  git:
      repo: 'https://github.com/fatih/vim-go'
      dest: '/home/{{ username }}/.vim/bundle/vim-go'

- name: Install fugitive
  git:
      repo: 'https://github.com/tpope/vim-fugitive'
      dest: '/home/{{ username }}/.vim/bundle/vim-fugitive'

- name: Make Workspace directory
  file:
      path: '/home/{{ username }}/Workspace'
      state: directory
      owner: '{{ username }}'
      group: '{{ groupname }}'
      mode: 0775
