---
- name: Generate Locale
  locale_gen:
    name: en_US.UTF-8
    state: present
  become: true
  become_method: sudo

- name: Set Timezone
  raw: "echo Europe/London > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata"
  become: true
  become_method: sudo

- name: Update apt-cache
  apt:
      update_cache: yes
  become: true
  become_method: sudo

- name: Install Curl
  apt:
      name: curl
      state: latest
  become: true
  become_method: sudo

- name: Install software-properties-common
  apt:
      name: software-properties-common
      state: latest
  become: true
  become_method: sudo

- name: Install build-essential
  apt:
      name: build-essential
      state: latest
  become: true
  become_method: sudo

- name: Install tmux
  apt:
      name: tmux
      state: latest
  become: true
  become_method: sudo

- name: Install bash-completion
  apt:
      name: bash-completion
      state: latest
  become: true
  become_method: sudo

- name: Install git
  apt:
      name: git-core
      state: latest
  become: true
  become_method: sudo

- name: Install vim
  apt:
      name: vim
      state: latest
  become: true
  become_method: sudo

- name: Install vim-gui-common
  apt:
      name: vim-gui-common
      state: latest
  become: true
  become_method: sudo

- name: Install vim-runtime
  apt:
      name: vim-runtime
      state: latest
  become: true
  become_method: sudo

- name: Install powerline
  apt:
      name: powerline
      state: latest
  become: true
  become_method: sudo

- name: Create dotfiles dir
  file:
      path: '/home/{{ username }}/.dotfiles'
      state: directory
      owner: {{ username }}
      group: {{ groupname }}
      mode: 0775

